// ===========================================================================
// C10 — the caller-facing sentences that are still hardcoded in code.
//
// The locale-pack architecture exists so that no words a patient hears ship
// inside a TypeScript file: an en-GB clinic must not hear US phrasing, and the
// consent artefact must record the wording the caller actually heard. Today
// about 80% of the receptionist's spoken lines are literals, against three
// `renderPackMessage` calls.
//
// This list is that debt, written down. `receptionistPackStrings.lint.test.ts`
// fails on any `message:` literal NOT on it, so the number can only go down:
// a new hardcoded sentence is a test failure, and migrating one to a
// `tool.*` / `consent.*` / `receptionist.degraded.*` pack key simply makes
// its entry unused.
//
// Package C owns the migration (C10 ⇄ X1-09 · X3-07 · X1-10 · X1-11). The
// booking / availability / handoff / consent path goes first; the rest is
// declared in the limitations register.
//
// Regenerated by hand only. If you are adding a line here, ask first whether
// the sentence belongs in a locale pack — it almost always does.
// ===========================================================================

/** Normalised literal text (whitespace collapsed; `${…}` for interpolations). */
export type HardcodedMessage = string;

export const HARDCODED_CALLER_MESSAGES: Record<string, HardcodedMessage[]> = {
  'server/lib/receptionist/liveTools.ts': [
    "A staff member needs to confirm the service or provider for this change.",
    "Cancellations require at least ${…} hours notice. I can connect you with the front desk.",
    "Changes require at least ${…} hours notice. I can connect you with the front desk.",
    "I cannot bind this request to the exact active call and booking configuration. Please contact the front desk.",
    "I cannot complete secure verification on this call. I can connect you with the front desk.",
    "I cannot continue identity verification on this call. Please contact the front desk.",
    "I cannot revalidate the active call and booking configuration. Please contact the front desk.",
    "I cannot safely save that preference automatically. I will end outreach on this call and route it to the front desk.",
    "I cannot securely identify that appointment. I can connect you with the front desk.",
    "I cannot securely prepare that appointment change. I can connect you with the front desk.",
    "I cannot validate that new time. I can connect you with the front desk.",
    "I cannot verify this location against the active booking campaign.",
    "I could not bind that preference to one configured receptionist disclosure. I will keep this call metadata-only and connect you with staff.",
    "I could not bind that preference to the exact clinic disclosure. I will keep this call metadata-only and connect you with staff.",
    "I could not record that preference. I will keep this call metadata-only and connect you with staff.",
    "I could not verify those details. Please try again or ask for the front desk.",
    "I created a request in the front desk queue. Staff have not acknowledged it yet. If a transfer option is available, I can try it next; no transfer has occurred yet, and the callback request remains open.",
    "I did not get a valid date and time. Please choose one of the times returned by availability.",
    "I don't see any openings on ${…}. Would a different day work?",
    "I need a team member to confirm the provider or service before I offer a time.",
    "I need a team member to confirm which attested clinic location you want before I offer a time.",
    "I need to prepare this exact cancellation and receive your explicit confirmation before I can make the change.",
    "I need to prepare this exact new time and receive your explicit confirmation before I can make the change.",
    "I recorded your request. We will not make further outreach calls to this number.",
    "I'm not able to help with that just yet.",
    "On ${…} I have ${…}. Which works best for you?",
    "Please confirm: you want to ${…}. Is that correct?",
    "Please verify your identity before I access an existing appointment.",
    "Thank you. Your identity is verified for this call.",
    "That appointment can no longer be changed automatically. I can connect you with the front desk.",
    "That appointment cannot be changed automatically. I can connect you with the front desk.",
    "That appointment changed while we were speaking. I can connect you with the front desk.",
    "That appointment is already cancelled.",
    "That time is no longer available. Please choose another.",
    "That time is outside the clinic scheduling window. Please choose another.",
    "That time was just taken. Please choose another.",
    "The call is marked booked without canonical appointment evidence. A staff member must review it.",
    "The existing booking evidence is inconsistent. A staff member must review it.",
    "The front desk has already reviewed this request. Please contact them for assistance.",
    "This appointment request already has a terminal staff decision. A staff member must review it.",
    "This call already has a different terminal outcome. A staff member must review it.",
    "This change requires the front desk.",
    "This clinic requires staff review before offering self-booking times.",
    "Your appointment is rescheduled to ${…}.${…}",
    "Your earlier refusal or withdrawal remains in effect for this call. I will keep it metadata-only and can connect you with staff.",
  ],
  'server/modules/receptionist/webhooks.ts': [
    "AI receptionist tool safety limit reached; staff review is required.",
    "I cannot safely complete this booking because the active intake configuration changed. I recorded a staff review request.",
    "I cannot safely confirm the required callback number from this call. I recorded a front desk review request.",
    "I cannot safely continue this automated request. I recorded a front desk review request; staff have not acknowledged it yet.",
    "I cannot safely select the booking campaign. I recorded a staff review request.",
    "I need your explicit agreement to the opening disclosure before I can access or change patient information. I can connect you with staff instead.",
    "I'm sorry, I can't access this clinic right now.",
    "I'm sorry, I can't safely continue this automated request. Please contact the front desk directly.",
    "I'm sorry, the clinic's verified receptionist configuration is no longer valid for this call. I cannot access or change patient information.",
    "I'm sorry, the verified receptionist configuration changed for this call. I cannot access or change patient information.",
    "I'm sorry, this call is not using the clinic's verified receptionist configuration. I cannot access or change patient information.",
    "I'm sorry, this call requires staff reconciliation and cannot continue.",
    "I'm sorry, this clinic's AI receptionist is unavailable right now. I can only direct you to staff.",
    "This call is no longer active. I cannot access or change patient information.",
  ],
};

/** Files the lint scans. Adding one here is how a new module joins the ratchet. */
export const PACK_STRING_LINT_FILES = Object.keys(HARDCODED_CALLER_MESSAGES);
