import 'dotenv/config';
import { randomUUID } from 'node:crypto';
const { PrismaPg } = await import('@prisma/adapter-pg');
const { PrismaClient } = await import('./generated/prisma/client');
const { buildApp } = await import('./app');
const { recomputeEntitlements } = await import('./lib/entitlements');
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_MIGRATION_URL ?? process.env.DATABASE_URL }) });
const id = randomUUID();
await db.tenant.create({ data: { id, name: 'dbg', slug: `dbg-${id.slice(0,8)}` } });
const plan = await db.subscriptionPlan.findUnique({ where: { key: 'enterprise' } });
await db.tenantSubscription.create({ data: { tenantId: id, planId: plan!.id, status: 'ACTIVE', startedAt: new Date() } });
await recomputeEntitlements(id);
const branch = await db.branch.create({ data: { tenantId: id, name: 'b', location: 'x' } });
const patient = await db.patient.create({ data: { tenantId: id, branchId: branch.id, firstName: 'P', lastName: 'Q', lifecycleStage: 'NEW' } });
const user = await db.user.create({ data: { tenantId: id, role: 'FRONT_DESK', active: true, email: `u-${id.slice(0,8)}@x.test`, displayName: 'u' } });
const app = await buildApp();
const t = app.jwt.sign({ userId: user.id, tenantId: id, role: 'ADMIN', type: 'access' });
const startsAt = new Date(Date.now()+4*86400000);
const appt = JSON.parse((await app.inject({ method:'POST', url:'/v1/appointments', headers:{ authorization:`Bearer ${t}`, 'x-forwarded-for':'9.9.9.9' }, payload:{ branchId: branch.id, patientId: patient.id, service:'Cleaning', startsAt: startsAt.toISOString(), endsAt: new Date(startsAt.getTime()+1800000).toISOString(), channel:'CALL', value:150 } })).body);
const res = await app.inject({ method:'POST', url:'/v1/revenue-protection/eligibility/check', headers:{ authorization:`Bearer ${t}`, 'x-forwarded-for':'9.9.9.8' }, payload:{ appointmentId: appt.id } });
console.log('STATUS', res.statusCode);
console.log('BODY', res.body.slice(0, 400));
await app.close();
await db.tenant.delete({ where: { id } }).catch(()=>{});
await db.$disconnect();
